### ISSUE TITLE
Command formula does not call base.update when shell returns successfully

### ISSUE THREAD

**Issue by evocateur** [toumorokoshi/sprinter#100]
https://github.com/toumorokoshi/sprinter/blob/e69c8bbd73b675674786565b1f50cb7bfc413138/sprinter/formula/command.py#L43

* During an install, `rc` and `env` (and other things managed by the formula base) are applied correctly.
* During an update, however, any `rc` or `env` fields are completely removed, instead of properly re-applied.

Even my cheesy workaround of returning non-zero from the `update` script won't help, because it only ever returns `True` unless you want it to throw an error.

**Comment by toumorokoshi** [comment]
Hey @evocateur, I pushed a fix which doesn't resolve the issue as specified, but I think fixed the intention.

rc/env should always be honored for install/update, regardless of the formula. The old methodology of calling superclasses require coder diligence and is error prone, so I moved that part out.

You should now see rc/env as long as command itself doesn't raise an exception during execution. 

I believe that fixes the functional bug. Thoughts?

**Comment by evocateur** [comment]
That should do it, thanks!
