### ISSUE TITLE
Leave a breadcrumb when a user deactivates sprinter

### ISSUE THREAD

**Issue by GreenGremlin** [toumorokoshi/sprinter#68]
We should leave a breadcrumb to reactivate sprinter when a user calls `sprinter deactivate sprinter`.

**Comment by GreenGremlin** [comment]
Possible solution:

```
#!/usr/bin/env bash
# $SPRINTER_ENV_ROOT would have to be a hard coded path, not an environment variable

# todo: Somehow detect if the sprinter environment is active.
# We can't trust the environment variables, because they may have
# just called `sprinter deactivate sprinter` and not re-env'd.
if [[ type sprinter >/dev/null 2>&1 ]]; then
    # pass through to active sprinter
    sprinter "$@"
    exit 0
fi

# sprinter is not active, the only valid command is `sprinter activate`
if [[ ! -e $SPRINTER_ENV_ROOT/sprinter ]]; then
    echo "Could not find sprinter root!"
    exit 1
fi
if [[ "$1" == "activate" && ! $2 ]]; then
    $SPRINTER_ENV_ROOT/sprinter/bin/sprinter
else
    echo " "
    echo "Sprinter has been deactivated!"
    echo " "
    echo "  run \`sprinter activate\` to reactivate sprinter"
fi
```

**Comment by GreenGremlin** [comment]
Maybe it doesn't matter if sprinter works fine in the existing terminal, after deactivating sprinter. I'm pretty sure that's the current behavior. Maybe we just always pass through, and catch the error if it fails.

**Comment by toumorokoshi** [comment]
I'm wondering if it should even be possible to disable sprinter at all. If we did leave breadcrumbing, I don't know where the right place would be. It seems against the philosophy of "deactivate" to still leaves files hanging around.

For now, we could just put that script in: ~/.sprinter/reactivate_sprinter script, maybe? You don't really need to check whether it's already active or not; activate is designed to be idempotent.

I don't know the best way to do that sprinter_env_root. Maybe for now we could just hard-code the variable to ~/.sprinter? It's really the only right place to put sprinter, anyway.

**Comment by GreenGremlin** [comment]
Maybe we just need to ensure that the only command that is exposed when sprinter is active is the sprinter command. I'm not exactly sure how it came to be, but at one point I was running pip 7.2.2 which led to sprinter installing and exposing pip 7.2.0. I ran `pip install --upgrade pip`, intending to upgrade my system pip. But actually upgraded sprinter's pip and broke sprinter. At the moment, there is not a copy of pip in ~/.sprinter/sprinter/bin and ~/.sprinter/sprinter/features/sprinter/bin is not in my PATH, but one of those two was the case at that time.

Currently for me pex, sprinter, virtualenv, virtualenv-3.5, and wheel are all exposed in ~/.sprinter/sprinter/bin. Is there really a need to expose anything other than sprinter?

**Comment by toumorokoshi** [comment]
huh, didn't mean to close that.

**Comment by toumorokoshi** [comment]
@GreenGremlin sprinter formula now only adds "sprinter", explicitly. how's that? https://github.com/toumorokoshi/sprinter/commit/c26a8c59d895f5efccb6f3019831dfaecbce2f61

**Comment by GreenGremlin** [comment]
Worked, thanks!!

``` shell
ls .sprinter/sprinter/bin/
sprinter
~
$
```
and
``` shell
$which pip
/usr/local/bin/pip
~
$which virtualenv
/usr/local/bin/virtualenv
~
$which pex
~
$
```
Awesome!
