### ISSUE TITLE
Template formula is confusing

### ISSUE THREAD

**Issue by GreenGremlin** [toumorokoshi/sprinter#69]
I assumed the template formula would allow me to have variables replaced in the downloaded file, but that appears to not be the case. Does the template formula really just download a file and place it in a target location? If so, would it make sense to have the option to format it using string.format, or maybe even parse it with something like Jinja?

**Comment by toumorokoshi** [comment]
it just downloads a file. I agree it could be better named. I'm not sure how well the .ini configs would support template variables, but if you wanted to do a PR to give it a shot, I'd be happy took over it :)
